import React from 'react'
import Head from 'next/head'

const HeadComponent = () => {
  return (
    
    <Head>
        <title>Netsooon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logonetsooon.svg" />
    </Head>
      
  )
}

export default HeadComponent